### ISSUE TITLE
handle supplemental config

### ISSUE THREAD

**Issue by maany** [simple-framework/simple_htcondor_ce#4]
Additional condor knobs can be specified in the supplemental config section of the site level configuration file.
```
lightweight_components:
  - name: HTCondorCE
     ..
     ..
     supplemental_config:
         - condor_ce: 
              - condor_knob: value
              - "raw string"
         - condor_schedd:
              - condor_knob: value
         - "/some/path/inside/container"
               - condor_knob: value 
```
